Remove electron-builder-notarize
The environment variables we are passing get picked by the built in notarization
code in electron-builder which signs successfully.

    notarization successful

But thereafter electron-builder-notarize starts throwing some errors:

    Error: The appleIdPassword property is required when using notarization with password credentials
        at validateNotaryToolAuthorizationArgs (/Users/runner/work/photos-desktop/photos-desktop/desktop/node_modules/electron-notarize/src/validate-args.ts:107:13)
    Skipping notarization: The appleIdPassword property is required when using notarization with appleId
        at module.exports (/Users/runner/work/photos-desktop/photos-desktop/desktop/node_modules/electron-builder-notarize/validate.js:42:18)

Since the notarization has already happened, we don't need this