[desktop] Fix macOS universal binaries
The previous approach worked, but we ran into some other issues

    Uncaught Exception:
    Error: Cannot find module 'ajv/dist/compile/codegen'
    Require stack:
    - /Applications/ente.app/Contents/Resources/app.asar/node_modules/ajv-formats/dist/limit.js

As an alternative, try to use the yarn equivalent(-ish).