Update to Next 14
This was because with 13.5 I was getting an error coming from emotion:

    Unhandled Runtime Error

    Error: Component selectors can only be used in conjunction with
    @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler
    transform.

    Call Stack
    - handleInterpolation
      ../node_modules/@emotion/serialize/dist/emotion-serialize.browser.esm.js (84:0)
    - serializeStyles
      ../node_modules/@emotion/serialize/dist/emotion-serialize.browser.esm.js (264:0)