Remove duplicate notarization attempt
From build logs:

     • notarization successful
    Error: The appleIdPassword property is required when using notarization with password credentials
        at validateNotaryToolAuthorizationArgs (/Users/runner/work/photos-desktop/photos-desktop/desktop/node_modules/electron-notarize/src/validate-args.ts:107:13)

Not sure, but at the face of it (since this was not enabled earlier too), our
notarization process kicks in during signing because of the presence of env
vars, and specifying it again here starts a separate process we haven't
configured.